# Generated by Django 2.2 on 2019-05-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_dish', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('ingredients', models.ManyToManyField(to='content.Ingredients')),
            ],
        ),
    ]
