# Generated by Django 2.2 on 2019-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
