# Generated by Django 2.2 on 2019-05-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190506_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dishes',
            name='dish_type',
            field=models.ManyToManyField(to='content.DishType'),
        ),
    ]
