# Generated by Django 2.2 on 2019-05-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_gallery_gallerycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
