# Generated by Django 2.2 on 2019-05-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_url',
            field=models.URLField(default='yes'),
            preserve_default=False,
        ),
    ]
