# Generated by Django 2.2 on 2019-06-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
