# Generated by Django 2.2 on 2019-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='position',
            field=models.CharField(default='CEO', max_length=100),
            preserve_default=False,
        ),
    ]
