# Generated by Django 2.2 on 2019-06-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='pub_date_comment',
        ),
    ]
