# Generated by Django 2.2 on 2019-06-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190605_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='com',
        ),
    ]
